services:
  - type: web
    name: vanscape-backend
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y findutils && npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://yasenroycey6:N3mIiEPid1UZ38u7@vansdata.bcteh7y.mongodb.net/VansData?retryWrites=true&w=majority
    rootDir: server/